BookMyShow/urls.py
from django.contrib import admin
from django.urls import path, include
from movies.views import SearchView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('auth.urls')),
    path('', include('movies.urls')),
    path('cinema/', include('cinema.urls')),
    path('tickets/', include('tickets.urls')),
    path('search/', SearchView.as_view(), name = 'search')
]

auth/urls.py
from django.urls import path

from auth import views

urlpatterns = [
    path('', views.LoginSignup.as_view(), name = 'loginsignup'),
    path('login/', views.Login, name = 'login'),
    path('signup/', views.SignUp, name = 'signup'),
    path('logout/', views.Logout, name = 'logout')
]

tickets/urls.py
from django.conf.urls import url
from django.urls import path
from tickets import views

# app_name = 'tickets'

urlpatterns = [
    path('seatchoice/<int:show_id>/', views.reserve_seat, name = "Reserve"),
    path('payment/', views.payment_gateway, name='payment_gateway'),
    path('payment_confirmation/', views.payment_confirmation, name = 'payment_confirmation'),
    path('', views.BookingListView.as_view(), name = 'list'),
    path('<int:btid>/delete/', views.BookingDeleteView.as_view(), name = 'delete'),
    path('<int:btid>/', views.BookingDetailView.as_view(), name = 'detail')
]

tickets/models.py
from django.db import models
from django.contrib.auth import get_user_model
from cinema.models import Show
from django.urls import reverse
from django.db.models.signals import post_delete
User = get_user_model()

# Create your models here.

class Booking(models.Model):
    payment_choice = (
        ('Debit Card', 'Debit Card'),
        ('Credit Card', 'Credit Card'),
        ('Net Banking', 'Net Banking'),
        ('Wallet', 'Wallet'),
    )
    id = models.CharField(primary_key=True, max_length=200)
    timestamp = models.DateTimeField('%Y-%m-%d %H:%M:%S')
    payment_type = models.CharField(max_length=11, choices=payment_choice)
    paid_amount = models.DecimalField(max_digits=8, decimal_places=2)
    paid_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('booking:detail',kwargs={'btid':self.id})
    

class Seat(models.Model):
    seat_choice = (
        ('', 'Select'),
        ('Silver', 'Silver'),
        ('Gold', 'Gold'),
        ('Platinum', 'Platinum'),
    )
    no = models.CharField(max_length=3)
    seat_type = models.CharField(max_length=8, choices=seat_choice, blank=False)
    show = models.ForeignKey(Show, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('no', 'show')

    def __str__(self):
        return self.no + str(self.show)


class BookedSeat(models.Model):
    seat = models.ForeignKey(Seat, on_delete=models.CASCADE)
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('seat', 'booking')

    def __str__(self):
        return str(self.seat) + '|' + str(self.booking)


def delete_reverse(sender,instance,*args,**kwargs):
    try:
        if instance.seat:
            instance.seat.delete()
    except:
        pass

post_delete.connect(delete_reverse,sender=BookedSeat)

tickets/forms.py
from django import forms
from tickets.models import Seat, Booking


class SeatForm(forms.ModelForm):

	class Meta:
		model = Seat
		fields = ('seat_type',)


class BookingForm(forms.ModelForm):

	class Meta:
		model = Booking
		fields = ('payment_type',)

tickets/views.py
from django.shortcuts import render, get_object_or_404
from tickets.models import Booking, BookedSeat, Seat
from cinema.models import Show
from tickets.forms import SeatForm, BookingForm
from django.urls import reverse_lazy
import datetime
from django.views.generic import ListView,DetailView,DeleteView
from cinema.models import Theatre
from django.shortcuts import redirect
from django.http.response import Http404

# Create your views here.

def reserve_seat(request, show_id):
    try:
        show_info = Show.objects.get(pk=show_id)
    except Theatre.DoesNotExist:
        raise Http404("Page does not exist")
    form = SeatForm()
    context = {
        'show_info': show_info, 
        'form': form
    }
    return render(request, 'tickets/reserve_seat.html', context)


def payment_gateway(request):
    if request.POST:
        seats = request.POST.get('selected_seat')
        seat_type = request.POST.get('seat_type')
        show_id = request.POST.get('show_id')

        show = Show.objects.get(pk=show_id)
        seats = seats.split(',')
        book_seat = []
        for each in seats:
            if Seat.objects.filter(no=each, show=show).exists():
                return render(request, 'tickets/reserve_seat.html', 
                    {'show_info': show, 'form': SeatForm()})
            s = Seat(no=each, seat_type=seat_type, show=show)
            book_seat.append(s)
        Seat.objects.bulk_create(book_seat)

        form = BookingForm()

        price_dict = {'Platinum': 300, 'Gold': 200, 'Silver': 100}
        ticket_price = price_dict[seat_type]*len(book_seat)

        seat_str = ""
        for i in range(0, len(seats)):
            if i == len(seats)-1:
                seat_str += seats[i]
            else:
                seat_str += seats[i] + ','

        return render(request, 'tickets/payment_gateway.html', 
            {'seats': seat_str, 'seat_type': seat_type, 
            'show': show, 'form': form, 'ticket_price': ticket_price})
    else:
        return redirect('cinema.views.theatre_list')


def payment_confirmation(request):
    if request.POST:
        show_id = request.POST.get('show_id')
        show = Show.objects.get(pk=show_id)
        seats = request.POST.get('selected_seat')
        seats = seats.split(',')
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        payment_type = request.POST.get('payment_type')
        paid_amount = request.POST.get('amount')
        paid_by = request.user
        id = str(show) + str(seats) + timestamp
        book = Booking(id=id, timestamp=timestamp, payment_type=payment_type, 
            paid_amount=paid_amount, paid_by=paid_by)
        book.save()

        booked_seat = []

        for seat in seats:
            print(seat)
            s = Seat.objects.get(no=seat, show=show)
            b = Booking.objects.get(pk=id)
            booked = BookedSeat(seat=s, booking=b)
            booked_seat.append(booked)

        BookedSeat.objects.bulk_create(booked_seat)

        return render(request, 'tickets/payment_confirmation.html')
    else:
        return redirect('cinema.views.theatre_list')


class BookingListView(ListView):
    def get_queryset(self):
        return Booking.objects.filter(paid_by=self.request.user)
    
class BookingDetailView(DetailView):
    def get_queryset(self):
        return Booking.objects.filter(paid_by=self.request.user)
    
    def get_object(self,*args,**kwargs):
        btid = self.kwargs.get('btid')
        obj = get_object_or_404(Booking,id=btid)
        return obj

class BookingDeleteView(DeleteView):
    model = Booking
    success_url = reverse_lazy('booking:list')    
    def get_object(self,*args,**kwargs):
        btid = self.kwargs.get('btid')
        obj = get_object_or_404(Booking,id=btid)
        return obj

templates/tickets/payment_confirmation.html
{% extends "base.html" %} {% block content %}

<h1>Payment Confirmation</h1>
<hr /><br /><br /><br /><br />
<p class="text-center text-success lead">Booking Done!</p>


{% endblock %}

templates/tickets/payment_gateway.html
{% extends "base.html" %} {% block content %}

<h1>Payment</h1>
<hr />
<div class="jumbotron" style="background-color:#add8e6">
    <div class="booking">
        <form method="post" action="{% url 'payment_confirmation' %}">
            {% csrf_token %}
            <input type="hidden" id="show_id" name="show_id" value="{{ show.id }}">
            <!--<pre>-->
            <div class="row">
                <div class="col-sm-offset-3 col-sm-1">
                    <label>Movie:</label>
                </div>
                <div class="col-sm-4">
                    <input id="movie" class="form form-control" name="movie" value="{{ show.movie }}" readonly><br /><br />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-offset-3 col-sm-1">
                    <label>Theatre:</label>
                </div>
                <div class="col-sm-4">
                    <input id="theatre" class="form form-control" name="theatre" value="{{ show.theatre }}" readonly><br /><br />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-offset-3 col-sm-1">
                    <label>Screen No:</label>
                </div>
                <div class="col-sm-4">
                    <input id="screen" class="form form-control" name="screen" value="{{ show.screen }}" readonly><br /><br />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-offset-3 col-sm-1">
                    <label>Showtime:</label>
                </div>
                <div class="col-sm-4">
                    <input id="showtime" class="form form-control" name="showtime" value="{{ show.time }}" readonly><br /><br />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-offset-3 col-sm-1">
                    <label>Date:</label>
                </div>
                <div class="col-sm-4">
                    <input id="date" class="form form-control" name="date" value="{{ show.date }}" readonly><br /><br />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-offset-3 col-sm-1">
                    <label>Seats:</label>
                </div>
                <div class="col-sm-4">
                    <input id="selected_seat" class="form form-control" name="selected_seat" value="{{ seats }}" readonly><br /><br />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-offset-3 col-sm-1">
                    <label>Seat Type:</label>
                </div>
                <div class="col-sm-4">
                    <input id="seat_type" class="form form-control" name="seat_type" value="{{ seat_type }}" readonly><br /><br />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-offset-3 col-sm-1">
                    <label>Payable Amount:</label>
                </div>
                <div class="col-sm-4">
                    <input id="amount" class="form form-control" name="amount" value="{{ ticket_price }}" readonly><br /><br />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-offset-5 col-sm-7">
                    {{ form.as_p }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-offset-5 col-sm-7">
                    <button class="btn btn-primary btn-lg" type="submit">Pay</button>
                </div>
            </div>
            <!--</pre>-->
        </form>
    </div>
</div>

{% endblock %}

templates/tickets/reserve_seat.html
{% extends "base.html" %} {% block content %}

<h1 style="color: white">Select Seats</h1>
<h2 style="color: white">{{ show_info }}</h2>
<div class="seatDiv">
    <div class="seatArray">
    </div>
    <div class="seatForm">
        <form method="post" action="{% url 'payment_gateway' %}">
            {% csrf_token %} {{ form.as_p }} Seats: <input name="selected_seat" id="selected_seat" type="text" readonly />
            <br /><br />
            <span style="color: white">Total number of seats: </span><span id="no_of_seats">0</span>
            <input type="hidden" style="color: white" name="show_id" id="show_id" value="{{ show_info.id }}" readonly />
            <br /><br />
            <button type="submit" class="btn btn-warning" style="color: white">Confirm</button>
        </form>
    </div>
</div>



<script>
    function createSeatArray() {
        var seats_per_row = 15;
        var seats = {
            'Platinum': 2,
            'Gold': 2,
            'Silver': 6
        };
        var rows = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O'];
        var seat_array = "<div id='seat_array'>";
        var count = 0;
        for (var key in seats) {
            seat_array += "<table class='" + key + "'>";
            for (var i = 0; i < seats[key]; i++) {
                seat_array += "<tr class='" + rows[count] + "'>";
                for (var j = 1; j <= seats_per_row; j++) {
                    seat_array += "<td><div class='" + key + "'><a>" + rows[count] + j + "</a></div></td>";
                }
                seat_array += "</tr>";
                count++;
            }
            seat_array += "</table>";
        }
        seat_array += "</div>";
        return seat_array;
    }


    $(document).ready(function() {

        //create seat array
        $('.seatArray').append(createSeatArray());

        //show available seats of particular type
        $('#id_seat_type').change(function() {
            seat_dict = {};
            $('#selected_seat').attr('value', '');
            $('.selectable').removeClass('selectable selected');
            var selector = $(this).val();
            $('table.' + selector + ' td div').addClass('selectable');
        });

        var seat_dict = {};

        //change color of selected seat
        $(document).on('click', 'div.selectable', function() {
            var curr_seat = $(this).text();
            if (curr_seat in seat_dict) {
                delete seat_dict[curr_seat];
            } else {
                seat_dict[curr_seat] = curr_seat;
            }
            $(this).toggleClass('selected');
            var selected_seat = [];
            for (var key in seat_dict) {
                selected_seat.push(key);
            }
            $('input#selected_seat').attr('value', selected_seat);
            $('#no_of_seats').text(selected_seat.length);
        });
    });
</script>

{% endblock %}